/* Static data maps used across pages */
const countryContinent = {
  "Japan":"Asia","United Kingdom":"Europe","Cuba":"North America","Sri Lanka":"Asia",
  "Germany":"Europe","Fiji":"Oceania","France":"Europe","Colombia":"South America",
  "Switzerland":"Europe","Sweden":"Europe","Italy":"Europe","Spain":"Europe",
  "Israel":"Asia","India":"Asia","Greece":"Europe","Ireland":"Europe",
  "Finland":"Europe","Brazil":"South America","Timor-Leste":"Asia","Kiribati":"Oceania",
  "Poland":"Europe","Norway":"Europe","Turkmenistan":"Asia","Saudi Arabia":"Asia",
  "Panama":"North America","Belgium":"Europe","Denmark":"Europe","Eswatini":"Africa",
  "Ukraine":"Europe","Nicaragua":"North America","Portugal":"Europe","Singapore":"Asia",
  "Nepal":"Asia","Samoa":"Oceania","North Korea":"Asia","Iceland":"Europe",
  "Cyprus":"Europe","Croatia":"Europe","Georgia":"Asia","Russia":"Europe",
  "Albania":"Europe","Pakistan":"Asia","Lebanon":"Asia","Iraq":"Asia",
  "Ecuador":"South America","Yemen":"Asia","Rwanda":"Africa","Bangladesh":"Asia",
  "Romania":"Europe","Slovakia":"Europe","Austria":"Europe","Netherlands":"Europe",
  "Luxembourg":"Europe","Czechia":"Europe","Liberia":"Africa","Iran":"Asia",
  "Estonia":"Europe","Vatican City":"Europe","Equatorial Guinea":"Africa","Syria":"Asia",
  "Malaysia":"Asia","Antigua and Barbuda":"North America","Indonesia":"Asia",
  "Dominican Republic":"North America","Slovenia":"Europe","Serbia":"Europe",
  "Taiwan":"Asia","Namibia":"Africa","North Macedonia":"Europe","Canada":"North America",
  "Hungary":"Europe","Saint Lucia":"North America","South Korea":"Asia","Guyana":"South America",
  "Latvia":"Europe","Bahamas":"North America","Bhutan":"Asia","Kosovo":"Europe",
  "Angola":"Africa","Democratic Republic of the Congo":"Africa","Uruguay":"South America",
  "Monaco":"Europe","Cambodia":"Asia","Qatar":"Asia","Afghanistan":"Asia",
  "Malta":"Europe","Micronesia":"Oceania","Zambia":"Africa","Tajikistan":"Asia",
  "Mexico":"North America","Bulgaria":"Europe","Belarus":"Europe","Bahrain":"Asia",
  "Zimbabwe":"Africa","Bosnia and Herzegovina":"Europe","Somalia":"Africa",
  "Paraguay":"South America","Sudan":"Africa","Kazakhstan":"Asia","Benin":"Africa",
  "Thailand":"Asia","Uzbekistan":"Asia","Mongolia":"Asia","Montenegro":"Europe",
  "Chad":"Africa","China":"Asia","Guinea-Bissau":"Africa","Australia":"Oceania",
  "Laos":"Asia","Madagascar":"Africa","Jordan":"Asia","Grenada":"North America",
  "San Marino":"Europe","Armenia":"Asia","Andorra":"Europe","Dominica":"North America",
  "Moldova":"Europe","Republic of the Congo":"Africa","Algeria":"Africa","Cabo Verde":"Africa",
  "Jamaica":"North America","Vietnam":"Asia","United Arab Emirates":"Asia","Belize":"North America",
  "Kuwait":"Asia","The Gambia":"Africa","Sierra Leone":"Africa","Argentina":"South America",
  "Liechtenstein":"Europe","Bolivia":"South America","Trinidad and Tobago":"North America",
  "Azerbaijan":"Asia","Lithuania":"Europe","Solomon Islands":"Oceania","Suriname":"South America",
  "Brunei":"Asia","Honduras":"North America","Burkina Faso":"Africa","Palau":"Oceania",
  "New Zealand":"Oceania","Gabon":"Africa","Oman":"Asia","Maldives":"Asia",
  "Guatemala":"North America","Kyrgyzstan":"Asia","Central African Republic":"Africa",
  "Niger":"Africa","El Salvador":"North America","Vanuatu":"Oceania","Mali":"Africa",
  "Uganda":"Africa","Marshall Islands":"Oceania","Togo":"Africa","Myanmar":"Asia",
  "Malawi":"Africa","United States":"North America","Libya":"Africa","Djibouti":"Africa",
  "Saint Kitts and Nevis":"North America","Tanzania":"Africa","Barbados":"North America",
  "Ivory Coast":"Africa","Chile":"South America","South Africa":"Africa","Türkiye":"Asia",
  "South Sudan":"Africa","Costa Rica":"North America","Tunisia":"Africa","Nauru":"Oceania",
  "Egypt":"Africa","Philippines":"Asia","Peru":"South America","Ghana":"Africa",
  "Mauritania":"Africa","Venezuela":"South America","Haiti":"North America","Cameroon":"Africa",
  "Tonga":"Oceania","Mauritius":"Africa","Morocco":"Africa","Burundi":"Africa",
  "Botswana":"Africa","Ethiopia":"Africa","Kenya":"Africa","Mozambique":"Africa",
  "Senegal":"Africa","Papua New Guinea":"Oceania","Nigeria":"Africa","Palestine":"Asia",
  "Comoros":"Africa","Seychelles":"Africa","Saint Vincent and the Grenadines":"North America",
  "Tuvalu":"Oceania","Guinea":"Africa","Eritrea":"Africa","São Tomé and Príncipe":"Africa",
  "Lesotho":"Africa"
};

const countryCapitals = {
  "Japan":"Tokyo","United Kingdom":"London","Cuba":"Havana","Sri Lanka":"Colombo",
  "Germany":"Berlin","Fiji":"Suva","France":"Paris","Colombia":"Bogotá",
  "Switzerland":"Bern","Sweden":"Stockholm","Italy":"Rome","Spain":"Madrid",
  "Israel":"Jerusalem","India":"New Delhi","Greece":"Athens","Ireland":"Dublin",
  "Finland":"Helsinki","Brazil":"Brasília","Timor-Leste":"Dili","Kiribati":"Tarawa",
  "Poland":"Warsaw","Norway":"Oslo","Turkmenistan":"Ashgabat","Saudi Arabia":"Riyadh",
  "Panama":"Panama City","Belgium":"Brussels","Denmark":"Copenhagen","Eswatini":"Mbabane",
  "Ukraine":"Kyiv","Nicaragua":"Managua","Portugal":"Lisbon","Singapore":"Singapore",
  "Nepal":"Kathmandu","Samoa":"Apia","North Korea":"Pyongyang","Iceland":"Reykjavik",
  "Cyprus":"Nicosia","Croatia":"Zagreb","Georgia":"Tbilisi","Russia":"Moscow",
  "Albania":"Tirana","Pakistan":"Islamabad","Lebanon":"Beirut","Iraq":"Baghdad",
  "Ecuador":"Quito","Yemen":"Sanaa","Rwanda":"Kigali","Bangladesh":"Dhaka",
  "Romania":"Bucharest","Slovakia":"Bratislava","Austria":"Vienna","Netherlands":"Amsterdam",
  "Luxembourg":"Luxembourg City","Czechia":"Prague","Liberia":"Monrovia","Iran":"Tehran",
  "Estonia":"Tallinn","Vatican City":"Vatican City","Equatorial Guinea":"Malabo","Syria":"Damascus",
  "Malaysia":"Kuala Lumpur","Antigua and Barbuda":"Saint John's","Indonesia":"Jakarta",
  "Dominican Republic":"Santo Domingo","Slovenia":"Ljubljana","Serbia":"Belgrade",
  "Taiwan":"Taipei","Namibia":"Windhoek","North Macedonia":"Skopje","Canada":"Ottawa",
  "Hungary":"Budapest","Saint Lucia":"Castries","South Korea":"Seoul","Guyana":"Georgetown",
  "Latvia":"Riga","Bahamas":"Nassau","Bhutan":"Thimphu","Kosovo":"Pristina",
  "Angola":"Luanda","Democratic Republic of the Congo":"Kinshasa","Uruguay":"Montevideo",
  "Monaco":"Monaco","Cambodia":"Phnom Penh","Qatar":"Doha","Afghanistan":"Kabul",
  "Malta":"Valletta","Micronesia":"Palikir","Zambia":"Lusaka","Tajikistan":"Dushanbe",
  "Mexico":"Mexico City","Bulgaria":"Sofia","Belarus":"Minsk","Bahrain":"Manama",
  "Zimbabwe":"Harare","Bosnia and Herzegovina":"Sarajevo","Somalia":"Mogadishu",
  "Paraguay":"Asunción","Sudan":"Khartoum","Kazakhstan":"Nur-Sultan","Benin":"Porto-Novo",
  "Thailand":"Bangkok","Uzbekistan":"Tashkent","Mongolia":"Ulaanbaatar","Montenegro":"Podgorica",
  "Chad":"N'Djamena","China":"Beijing","Guinea-Bissau":"Bissau","Australia":"Canberra",
  "Laos":"Vientiane","Madagascar":"Antananarivo","Jordan":"Amman","Grenada":"Saint George's",
  "San Marino":"San Marino","Armenia":"Yerevan","Andorra":"Andorra la Vella","Dominica":"Roseau",
  "Moldova":"Chișinău","Republic of the Congo":"Brazzaville","Algeria":"Algiers","Cabo Verde":"Praia",
  "Jamaica":"Kingston","Vietnam":"Hanoi","United Arab Emirates":"Abu Dhabi","Belize":"Belmopan",
  "Kuwait":"Kuwait City","The Gambia":"Banjul","Sierra Leone":"Freetown","Argentina":"Buenos Aires",
  "Liechtenstein":"Vaduz","Bolivia":"Sucre","Trinidad and Tobago":"Port of Spain",
  "Azerbaijan":"Baku","Lithuania":"Vilnius","Solomon Islands":"Honiara","Suriname":"Paramaribo",
  "Brunei":"Bandar Seri Begawan","Honduras":"Tegucigalpa","Burkina Faso":"Ouagadougou","Palau":"Ngerulmud",
  "New Zealand":"Wellington","Gabon":"Libreville","Oman":"Muscat","Maldives":"Malé",
  "Guatemala":"Guatemala City","Kyrgyzstan":"Bishkek","Central African Republic":"Bangui",
  "Niger":"Niamey","El Salvador":"San Salvador","Vanuatu":"Port Vila","Mali":"Bamako",
  "Uganda":"Kampala","Marshall Islands":"Majuro","Togo":"Lomé","Myanmar":"Naypyidaw",
  "Malawi":"Lilongwe","United States":"Washington, D.C.","Libya":"Tripoli","Djibouti":"Djibouti",
  "Saint Kitts and Nevis":"Basseterre","Tanzania":"Dodoma","Barbados":"Bridgetown",
  "Ivory Coast":"Yamoussoukro","Chile":"Santiago","South Africa":"Cape Town","Türkiye":"Ankara",
  "South Sudan":"Juba","Costa Rica":"San José","Tunisia":"Tunis","Nauru":"Yaren",
  "Egypt":"Cairo","Philippines":"Manila","Peru":"Lima","Ghana":"Accra",
  "Mauritania":"Nouakchott","Venezuela":"Caracas","Haiti":"Port-au-Prince","Cameroon":"Yaoundé",
  "Tonga":"Nuku'alofa","Mauritius":"Port Louis","Morocco":"Rabat","Burundi":"Gitega",
  "Botswana":"Gaborone","Ethiopia":"Addis Ababa","Kenya":"Nairobi","Mozambique":"Maputo",
  "Senegal":"Dakar","Papua New Guinea":"Port Moresby","Nigeria":"Abuja","Palestine":"Ramallah",
  "Comoros":"Moroni","Seychelles":"Victoria","Saint Vincent and the Grenadines":"Kingstown",
  "Tuvalu":"Funafuti","Guinea":"Conakry","Eritrea":"Asmara","São Tomé and Príncipe":"São Tomé",
  "Lesotho":"Maseru"
};

const countries = Object.keys(countryContinent).sort();

const alpha2Overrides = {
  "Afghanistan":"af","Albania":"al","Algeria":"dz","Andorra":"ad",
  "Angola":"ao","Antigua and Barbuda":"ag","Argentina":"ar","Armenia":"am",
  "Australia":"au","Austria":"at","Azerbaijan":"az","Bahamas":"bs",
  "Bahrain":"bh","Bangladesh":"bd","Barbados":"bb","Belarus":"by",
  "Belgium":"be","Belize":"bz","Benin":"bj","Bhutan":"bt",
  "Bolivia":"bo","Bosnia and Herzegovina":"ba","Botswana":"bw","Brazil":"br",
  "Brunei":"bn","Bulgaria":"bg","Burkina Faso":"bf","Burundi":"bi",
  "Cabo Verde":"cv","Cambodia":"kh","Cameroon":"cm","Canada":"ca",
  "Central African Republic":"cf","Chad":"td","Chile":"cl","China":"cn",
  "Colombia":"co","Comoros":"km","Costa Rica":"cr","Croatia":"hr",
  "Cuba":"cu","Cyprus":"cy","Czechia":"cz","Democratic Republic of the Congo":"cd",
  "Denmark":"dk","Djibouti":"dj","Dominica":"dm","Dominican Republic":"do",
  "Ecuador":"ec","Egypt":"eg","El Salvador":"sv","Equatorial Guinea":"gq",
  "Eritrea":"er","Estonia":"ee","Eswatini":"sz","Ethiopia":"et",
  "Fiji":"fj","Finland":"fi","France":"fr","Gabon":"ga",
  "Georgia":"ge","Germany":"de","Ghana":"gh","Greece":"gr",
  "Grenada":"gd","Guatemala":"gt","Guinea":"gn","Guinea-Bissau":"gw",
  "Guyana":"gy","Haiti":"ht","Honduras":"hn","Hungary":"hu",
  "Iceland":"is","India":"in","Indonesia":"id","Iran":"ir",
  "Iraq":"iq","Ireland":"ie","Israel":"il","Italy":"it",
  "Ivory Coast":"ci","Jamaica":"jm","Japan":"jp","Jordan":"jo",
  "Kazakhstan":"kz","Kenya":"ke","Kiribati":"ki","Kosovo":"xk",
  "Kuwait":"kw","Kyrgyzstan":"kg","Laos":"la","Latvia":"lv",
  "Lebanon":"lb","Lesotho":"ls","Liberia":"lr","Libya":"ly",
  "Liechtenstein":"li","Lithuania":"lt","Luxembourg":"lu","Madagascar":"mg",
  "Malawi":"mw","Malaysia":"my","Maldives":"mv","Mali":"ml",
  "Malta":"mt","Marshall Islands":"mh","Mauritania":"mr","Mauritius":"mu",
  "Mexico":"mx","Micronesia":"fm","Moldova":"md","Monaco":"mc",
  "Mongolia":"mn","Montenegro":"me","Morocco":"ma","Mozambique":"mz",
  "Myanmar":"mm","Namibia":"na","Nauru":"nr","Nepal":"np",
  "Netherlands":"nl","New Zealand":"nz","Nicaragua":"ni","Niger":"ne",
  "Nigeria":"ng","North Korea":"kp","North Macedonia":"mk","Norway":"no",
  "Oman":"om","Pakistan":"pk","Palau":"pw","Palestine":"ps",
  "Panama":"pa","Papua New Guinea":"pg","Paraguay":"py","Peru":"pe",
  "Philippines":"ph","Poland":"pl","Portugal":"pt","Qatar":"qa",
  "Republic of the Congo":"cg","Romania":"ro","Russia":"ru","Rwanda":"rw",
  "Saint Kitts and Nevis":"kn","Saint Lucia":"lc","Saint Vincent and the Grenadines":"vc",
  "Samoa":"ws","San Marino":"sm","São Tomé and Príncipe":"st","Saudi Arabia":"sa",
  "Senegal":"sn","Serbia":"rs","Seychelles":"sc","Sierra Leone":"sl",
  "Singapore":"sg","Slovakia":"sk","Slovenia":"si","Solomon Islands":"sb",
  "Somalia":"so","South Africa":"za","South Korea":"kr","South Sudan":"ss",
  "Spain":"es","Sri Lanka":"lk","Sudan":"sd","Suriname":"sr",
  "Sweden":"se","Switzerland":"ch","Syria":"sy","Taiwan":"tw",
  "Tajikistan":"tj","Tanzania":"tz","Thailand":"th","The Gambia":"gm",
  "Timor-Leste":"tl","Togo":"tg","Tonga":"to","Trinidad and Tobago":"tt",
  "Tunisia":"tn","Turkmenistan":"tm","Türkiye":"tr","Tuvalu":"tv",
  "Uganda":"ug","Ukraine":"ua","United Arab Emirates":"ae","United Kingdom":"gb",
  "United States":"us","Uruguay":"uy","Uzbekistan":"uz","Vanuatu":"vu",
  "Vatican City":"va","Venezuela":"ve","Vietnam":"vn","Yemen":"ye",
  "Zambia":"zm","Zimbabwe":"zw"
};

const countryAliases = {
  "United States":["usa","us","america","united states of america"],
  "Vatican City":["vatican"],
  "Saint Vincent and the Grenadines":["st vincent","saint vincent"],
  "United Kingdom":["uk","gb","great britain","britain"],
  "Papua New Guinea":["png"],
  "São Tomé and Príncipe":["sao tome","sao"],
  "Saint Kitts and Nevis":["st kitts"],
  "Republic of the Congo":["congo","rep congo"],
  "Democratic Republic of the Congo":["drc","congo drc","congo kinshasa"],
  "Central African Republic":["car"],
  "North Korea":["dprk"],
  "United Arab Emirates":["uae"],
  "Türkiye":["turkey"],
  "North Macedonia":["macedonia"],
  "South Africa":["rsa"],
  "The Gambia":["gambia"]
};

const capitalAliases = {
  "Washington, D.C.":["washington","dc","washington dc"],
  "New Delhi":["delhi"],
  "Vatican City":["vatican"],
  "Luxembourg City":["luxembourg"],
  "Kuwait City":["kuwait"],
  "Panama City":["panama"],
  "Guatemala City":["guatemala"],
  "Mexico City":["mexico"],
  "Saint John's":["st johns","saint johns"],
  "Saint George's":["st georges","saint georges"],
  "Port of Spain":["port-of-spain","port of spain"],
  "San José":["san jose"],
  "São Tomé":["sao tome"],
  "N'Djamena":["ndjamena"],
  "Nur-Sultan":["nur sultan","astana"],
  "Bandar Seri Begawan":["bsb"]
};

const LS_KEYS = {
  reviseFlags:"revise_flags",
  reviseCapitals:"revise_capitals",
  highScores:"high_scores",
  sessionPercentages:"session_percentages"
};
